# app/region_metadata.py

REGION_METADATA = {
    "5ec4e10998603520ceb30fe5": {
        "country": "The Bahamas",
        "countryCd": "BS",
        "locations": [
            "The Bahamas",
            "Tarpum Bay",
            "Great Guana Cay",
            "Spanish Cay",
            "Sweetings Cay",
            "Clarence Town",
            "Atlantis Lagoon",
            "George Town",
            "Hooper's Bay",
            "Pierres Island",
            "Whitehouse",
            "Bahamas",
            "South Eleuthera",
            "The Berry Islands",
            "Exuma",
            "Hartswell",
            "Stocking Island",
            "Moore's Island",
            "Great Abaco",
            "Port Royal",
            "Elbow Cay",
            "Middle Cay",
            "Hope Town",
            "Holmes Rock",
            "South Andros",
            "Governor's Harbour",
            "Little Harbour Cay",
            "North Andros",
            "The Bahamas",
            "Stella Maris",
            "Freeport",
            "Michelson",
            "Rolletown",
            "Inagua",
            "Current",
            "Lucaya",
            "Nassau",
            "Landrail Point Settlement",
            "Upper Bogue",
            "Grand Cay",
            "Lubbers Quarters Cay",
            "Spanish Wells",
            "Adelaide",
            "Farmer's Hill",
            "Nassau - Paradise Island",
            "Castaway Cay",
            "Carmichael Village",
            "Conch Sound Settlement",
            "Crooked Island and Long Cay",
            "Crossing Rocks",
            "Big Whale Cay",
            "Alice Town",
            "Central Eleuthera",
            "West Grand Bahama",
            "Norman Castle",
            "Great Harbour Cay",
            "Doctor's Creek Settlement",
            "Highborne Cay",
            "The Bight",
            "Rum Cay",
            "Tilloo Cay",
            "Steventon",
            "Rock Sound",
            "Treasure Cay",
            "Man Island",
            "Green Turtle Cay",
            "North Palmetto Point",
            "Waterford",
            "Savannah Sound",
            "Bailey Town",
            "The Bluff",
            "Crown Haven",
            "Moore Hill",
            "San Salvador",
            "CocoCay",
            "Calvin Hill",
            "Andros",
            "Major's Cay Settlement",
            "Arthur's Town",
            "Behring Point Settlement",
            "Forbes Hill",
            "Great Stirrup Cay",
            "Man-O-War Cay",
            "Harbour Island",
            "Bimini",
            "Gregory Town",
            "Crooked Island",
            "Long Island",
            "Marsh Harbour",
            "Nicholls Town",
            "Hilton At Resorts World Bimini",
            "Central Andros",
            "Rolleville",
            "Hope Estate",
            "Dunmore Town",
            "Rokers Point Settlement",
            "East Grand Bahama",
            "Sandy Point",
            "Compass Cay",
            "Moss Town",
            "High Rock",
            "Chesters",
            "Little Exuma",
            "John Millars",
            "Mayaguana",
            "Nasáu",
            "Cat Island",
            "Salina Point Settlement",
            "The Exumas",
            "Staniel Cay",
            "Exuma Cays",
            "Pig Beach",
            "Cabbage Point Settlement",
            "West End",
            "Andros Island",
            "High Rock Settlement",
            "Gordon's Settlement",
            "Ragged Island",
            "Paradise Island",
            "Sam McKinnons Settlement",
            "Great Exuma Island",
            "Acklins & Crooked Islands",
            "Mangrove Cay",
            "The Abacos",
            "Eleuthera & Harbour Island",
            "North Eleuthera",
            "Peterson Cay",
            "Chub Cay"
        ],
        "experiences": [
            "Beaches",
            "DAY TRIPS & EXCURSIONS",
            "WATER SPORTS",
            "CANOE & KAYAK TOURS",
            "BEACH TRIPS",
            "DAY TRIPS",
            "RENTALS",
            "SNORKELING",
            "HISTORY & HERITAGE",
            "SHORE EXCURSIONS",
            "DOLPHIN & WHALE WATCHING",
            "DIVING",
            "BOAT TOURS & WATER SPORTS",
            "NATURE & PARKS",
            "OUTDOOR ACTIVITIES",
            "BEACH",
            "Cultural Immersion",
            "SURFING LESSONS",
            "DINNER SHOWS",
            "COFFEE TOURS",
            "NAPOLEON",
            "GHOST & VAMPIRE TOURS",
            "CHURCHES & CATHEDRALS",
            "EDUCATIONAL ACTIVITIES",
            "STREET MUSIC",
            "UNESCO SITES",
            "RELIGIOUS & SPIRITUAL ACTIVITIES",
            "MUSEUMS & EXHIBITIONS",
            "GRAFFITI & URBAN ART",
            "CABLECAR TOURS",
            "ART NOUVEAU",
            "SOCCER TICKETS",
            "CULTURE & HISTORY",
            "MUSEUM TICKETS",
            "FLAMENCO",
            "THEATER",
            "TEAM SPORTS",
            "COLD WAR",
            "ARCHITECTURE",
            "LOCAL FLAVOR & NEIGHBORHOOD TOURS",
            "FRENCH REVOLUTION",
            "ARCHAEOLOGY",
            "CONCERTS & OPERAS",
            "MUSICALS",
            "COOKING CLASSES",
            "SPECIALTY FOOD",
            "BUBBLE TEA",
            "PANZEROTTI",
            "STREET VENDORS",
            "FARMERS MARKET",
            "FISHMONGER",
            "DO-IT-YOURSELF FOOD",
            "MUSEUMS",
            "ZOOS & AQUARIUM",
            "CLASSES & WORKSHOPS",
            "CULTURAL & THEME TOURS",
            "STREET FOOD TOURS",
            "MARKET TOURS",
            "CHOCOLATE TOURS",
            "DINING EXPERIENCES",
            "DINNER THEATER",
            "FOOD TOURS",
            "COFFEE & TEA TOURS",
            "AFTERNOON TEAS",
            "LOCAL CULTURE",
            "SHOPPING - AUTHENTICALLY BAHAMIAN",
            "Romance",
            "BALLOON TOURS",
            "CRUISES & BOAT TOURS",
            "RIVER & HARBOR CRUISES",
            "WELLNESS & SPAS",
            "ROMANCE & SPECIAL OCCASIONS",
            "WEDDING PROPOSALS",
            "HONEYMOON",
            "DINNER PACKAGE",
            "WINE TASTING & WINERY TOURS",
            "DINNER & LUNCH CRUISES",
            "SHOWS & MUSICALS",
            "ADULTS ONLY",
            "VALENTINE'S DAY",
            "ROMANTIC",
            "PRIVATE EXPERIENCES",
            "COUPLES",
            "ROMANTIC TOURS",
            "SPECIAL OCCASIONS",
            "OUTDOOR SEATING",
            "SPA",
            "SHOPPING STREET",
            "SPAS & WELLNESS",
            "SCENIC VIEW",
            "Natural Wonders",
            "WATER & AMUSEMENT PARKS",
            "ISLAND TOURS",
            "SIGHTSEEING ATTRACTION TICKETS",
            "CRUISES, SAILING & WATER TOURS",
            "NATURE & WILDLIFE",
            "ECO TOURS",
            "HIKING & CAMPING",
            "FISHING CHARTERS & TOURS",
            "OUTDOORS & NATURE",
            "DIVING & SNORKELING",
            "Family Fun",
            "SIGHTSEEING TOURS",
            "THEME TOURS",
            "ART & MUSEUMS",
            "DESERT SAFARIS",
            "CITY CARDS",
            "SLEIGH RIDES",
            "THEME PARKS & AMUSEMENT PARKS",
            "ZOO & AQUARIUM",
            "HORSE & CARRIAGE TOURS",
            "CAMEL RIDING TOURS",
            "CHILDREN'S ACTIVITIES",
            "DEALS & DISCOUNTS",
            "HARRY POTTER TOURS",
            "WHEELCHAIR ACCESSIBLE",
            "FAMILY-FRIENDLY",
            "GONDOLA TOURS",
            "ICE CREAM",
            "MULTIPLE ATTRACTION POI",
            "THEME PARKS",
            "FAMILY-FRIENDLY SHOWS",
            "KIDS + FAMILIES",
            "SHOPPING",
            "FAMILY FRIENDLY",
            "KID FRIENDLY",
            "PLAYING",
            "THEME PARK",
            "AMUSEMENT PARK",
            "WATER PARK",
            "ZOO",
            "FERRIS WHEEL",
            "SWIMMING",
            "Adventures at Sea",
            "AIRBOAT TOURS",
            "SPEED & JET BOAT TOURS",
            "SEAPLANE",
            "BOATS & YACHTS",
            "FUN & GAMES",
            "HIKING",
            "BOATING",
            "FISHING",
            "Experiential",
            "SEGWAY TOURS",
            "BIKE TOURS",
            "MEET THE LOCALS",
            "URBAN EXPLORATION",
            "VIEWING POINTS",
            "OFF THE BEATEN TRACK",
            "UNIQUE EXPERIENCES",
            "ONCE IN A LIFETIME EXPERIENCES",
            "LIVE ENTERTAINMENT",
            "BIRDING",
            "SIGHTSEEING",
            "DISCOVERING",
            "EXPERIENCES",
            "Slow-Travel",
            "WALKING TOURS",
            "PHOTOGRAPHY TOURS",
            "SUNRISE TOURS",
            "SUNSET TOURS",
            "ANIMAL USE",
            "VIATOR VIP & EXCLUSIVE TOURS",
            "MULTI-DAY & EXTENDED TOURS",
            "CLASSES/WORKSHOPS",
            "RELAXING",
            "SLOW TRAVEL",
            "BIKE",
            "BIKING",
            "CULTURAL EVENTS",
            "BICYCLE & SCOOTER RENTALS",
            "HEALTH & WELLNESS",
            "Budget-Boutique",
            "SIGHT-JOGGING",
            "HOP-ON HOP-OFF TOURS",
            "FREE TOURS",
            "BUDGET",
            "PUBLIC TRANSPORTATION TICKET",
            "SIGHTSEEING TICKETS & PASSES",
            "BUDGET-FRIENDLY",
            "OUTDOORS",
            "BICYCLE RENTAL",
            "FREE",
            "ATTRACTIONS",
            "Luxury",
            "PRIVATE CAR TOURS",
            "SHOPPING TOURS",
            "SAFARIS & WILDLIFE ACTIVITIES",
            "AIR & HELICOPTER TOURS",
            "SAILING TRIPS & BOAT TOURS",
            "SWIM WITH DOLPHINS",
            "LUXURY & SPECIAL OCCASIONS",
            "NIGHT CLUB",
            "$$$$",
            "All-Inclusive",
            "BUS & MINIVAN TOURS",
            "JEEP & 4WD TOURS",
            "TRANSPORTATION",
            "AIRPORT TRANSFERS",
            "GROUP ACTIVITIES",
            "SMALL GROUP",
            "CITY PACKAGES",
            "DINNER PACKAGES",
            "SIGHTSEEING PACKAGES",
            "SPORTING EVENTS & PACKAGES",
            "ENTERTAINMENT PACKAGES",
            "WEDDING PACKAGES",
            "FITNESS",
            "WELLNESS",
            "PACKAGES",
            "ALL INCLUSIVE",
            "Art Museum",
            "MUSEUM TICKETS & PASSES",
            "ART CLASSES",
            "LITERARY, ART & MUSIC TOURS",
            "ART GALLERIES",
            "ARTS AND CRAFT",
            "Cultural & History",
            "Nature & Eco-Tourism",
            "ECOTOURISM",
            "ECO CERTIFIED",
            "NATURE RESERVE",
            "NATURE & PANORAMA",
            "Festivals & Celebrations",
            "NIGHTCLUB TICKETS",
            "NEW YEAR'S ACTIVITIES",
            "SEASONAL & HOLIDAY ACTIVITIES",
            "MUSIC ACTIVITIES",
            "NIGHTCLUB TOURS",
            "PARTY TOURS",
            "BEER BIKE",
            "PUB CRAWLS & BAR TOURS",
            "HOLIDAY & SEASONAL TOURS",
            "SHOWS, CONCERTS & SPORTS",
            "SEASONAL EVENTS",
            "CONCERTS & SPECIAL EVENTS",
            "NIGHTCLUB PASSES",
            "NIGHTLIFE",
            "BARS & PUBS",
            "CENOTE DIVING",
            "SHARK DIVING",
            "SWIMMING WITH TURTLES",
            "SCUBA DIVING",
            "FISHING TOURS",
            "BOAT PARTY",
            "GLASS BOTTOM BOAT TOURS",
            "JET BOATS & SPEED BOATS",
            "BOAT RENTAL",
            "Culinary",
            "FOOD & GOURMET TOURS",
            "FOOD & DRINKS",
            "CRÊPES",
            "PASTRY TOURS",
            "STREET FOOD",
            "BAKING",
            "CHOCOLATE",
            "FISH FRY EXPERIENCE",
            "Nightlife & Bars",
            "COMEDY TOURS",
            "WHISKEY TOURS",
            "BEER & BREWERY TOURS",
            "Beaches & Island Hopping",
            "SUBMARINE TOURS",
            "PARASAILING",
            "WATER TAXI",
            "JET-SKIS",
            "INTER-ISLAND FLIGHTS",
            "SHORE EXCURSION",
            "DAY EXCURSION",
            "DAY EXCURSIONS",
            "Spa & Wellness",
            "SPA TOURS",
            "DAY SPAS",
            "THERMAL SPAS & HOT SPRINGS"
        ]
    },

    "5df6e88dd2e86e50bc52fee7": {
        "country": "Mexico",
        "countryCd": "MX",
        "locations": [
            "Loreto",
            "Mulegé",
            "San Juanico",
            "Comondú",
            "Guerrero Negro",
            "San Ignacio",
            "Santa Rosalía",
            "Santa Martha",
            "Bay of Conception",
            "Las Tres Vírgenes",
            "San Bruno",
            "Isla Danzante",
            "Loreto Bay National Park"
        ],
        "experiences": [
            "Bliss",
            "SPAS & WELLNESS",
            "SIGHT-JOGGING",
            "WELLNESS & SPAS",
            "DAY SPA",
            "FITNESS & HEALTH",
            "SPIRITUAL WELLNESS",
            "HOT SPRINGS",
            "JAZZ",
            "WHEELCHAIR ACCESSIBLE",
            "SPA TOURS",
            "RELAXING",
            "WELLNESS",
            "SANDY BEACH",
            "GARDEN",
            "SPA",
            "SWIMMING",
            "Cultural Immersion",
            "CASTLE & PALACE TOURS",
            "LOCAL FLAVOR & NEIGHBORHOOD TOURS",
            "CULTURE & HISTORY",
            "ART & MUSEUMS",
            "ARCHITECTURE",
            "GRAFFITI & URBAN ART",
            "ARCHAEOLOGY",
            "HISTORY & HERITAGE",
            "MEET THE LOCALS",
            "SIGHTSEEING ATTRACTION TICKETS",
            "PEDICAB & RICKSHAW TOURS",
            "CAMEL RIDING TOURS",
            "CARNIVAL ACTIVITIES",
            "CHURCHES & CATHEDRALS",
            "COLD WAR",
            "LOCAL LANGUAGE",
            "SECOND WORLD WAR",
            "UNESCO SITES",
            "ART NOUVEAU",
            "FESTIVAL OF LIGHTS",
            "CULTURAL & THEME TOURS",
            "DISCOVERING",
            "SIGHTSEEING",
            "HIDDEN GEM",
            "HISTORICAL",
            "HERITAGE",
            "ARTWORK",
            "MUSEUMS",
            "SCENIC OUTLOOK",
            "FILMING LOCATION",
            "ART GALLERY",
            "BRIDGE",
            "MONUMENT",
            "SHOPPING STREET",
            "STREET ART",
            "MUSEUM",
            "Romance",
            "BALLOON TOURS",
            "CRUISES & BOAT TOURS",
            "RIVER & HARBOR CRUISES",
            "BEACH TRIPS",
            "ROMANCE & SPECIAL OCCASIONS",
            "WEDDING PROPOSALS",
            "HONEYMOON",
            "DINNER PACKAGE",
            "WINE TASTING & WINERY TOURS",
            "DINNER & LUNCH CRUISES",
            "SHOWS & MUSICALS",
            "DINNER SHOWS",
            "ADULTS ONLY",
            "CONCERTS & OPERAS",
            "VALENTINE'S DAY",
            "ROMANTIC",
            "PRIVATE EXPERIENCES",
            "COUPLES",
            "ROMANTIC TOURS",
            "OUTDOOR SEATING",
            "THEATER",
            "BEACH",
            "Natural Wonders",
            "OUTDOORS",
            "NATURE TRAIL",
            "WILDLIFE",
            "BIRD WATCHING",
            "BIRD SANCTUARY",
            "DIVING",
            "CLIFF DIVING",
            "HIKING",
            "BOAT TOURS & WATER SPORTS",
            "NATURE & PARKS",
            "OUTDOOR ACTIVITIES",
            "NATURE & ADVENTURE",
            "NATIONAL PARKS",
            "DESERT SAFARIS",
            "SAFARIS & WILDLIFE ACTIVITIES",
            "NATURE & PANORAMA",
            "BIRDWATCHING",
            "DOLPHIN & WHALE WATCHING",
            "SNORKELING",
            "TREKKING",
            "NATURAL ATTRACTIONS & NATIONAL PARKS",
            "GARDEN & PARK TOURS",
            "GARDENS & FLOWERS",
            "JUNGLE TOURS",
            "VOLCANO ACTIVITIES",
            "VIEWING POINTS",
            "SUNRISE TOURS",
            "ECOTOURISM",
            "SUNSET TOURS",
            "GLACIER EXPLORATION",
            "CAVE EXPLORATION",
            "NORTHERN LIGHTS",
            "AURORA BOREALIS",
            "NATURE & WILDLIFE",
            "Family",
            "SIGHTSEEING TOURS",
            "THEME TOURS",
            "CITY CARDS",
            "SLEIGH RIDES",
            "THEME PARKS & AMUSEMENT PARKS",
            "ZOO & AQUARIUM",
            "SOCCER TICKETS",
            "HORSE & CARRIAGE TOURS",
            "EDUCATIONAL ACTIVITIES",
            "CHILDREN'S ACTIVITIES",
            "DEALS & DISCOUNTS",
            "HARRY POTTER TOURS",
            "FAMILY-FRIENDLY",
            "GONDOLA TOURS",
            "ICE CREAM",
            "MULTIPLE ATTRACTION POI",
            "THEME PARKS",
            "FAMILY-FRIENDLY SHOWS",
            "FAMILY FRIENDLY",
            "KID FRIENDLY",
            "PLAYING",
            "THEME PARK",
            "AMUSEMENT PARK",
            "WATER PARK",
            "ZOO",
            "FERRIS WHEEL",
            "Festivals & Parties",
            "NIGHT TOURS",
            "HALLOWEEN ACTIVITIES",
            "CULINARY & NIGHTLIFE",
            "FOOD & DRINKS",
            "NIGHTLIFE & BARS",
            "PUB CRAWLS & BAR TOURS",
            "NIGHTCLUB TOURS",
            "NIGHTCLUB TICKETS",
            "MUSICALS",
            "PARTY TOURS",
            "CABARET",
            "STREET MUSIC",
            "THE BEATLES",
            "LUAUS",
            "HOLIDAY & SEASONAL TOURS",
            "NIGHTLIFE",
            "GOING OUT",
            "CONCERTS & SHOWS",
            "EVENTS",
            "FUN & GAMES",
            "Gastronomy",
            "FOOD & GOURMET TOURS",
            "WHISKEY TOURS",
            "COOKING CLASSES",
            "TAPAS",
            "CHOCOLATE",
            "STREET FOOD",
            "PASTRY TOURS",
            "COFFEE TOURS",
            "CRÊPES",
            "PAELLA",
            "LOCAL FOOD",
            "FOOD, WINE & NIGHTLIFE",
            "eating",
            "restaurant",
            "cafe",
            "Adventure",
            "WALKING TOURS",
            "SEGWAY TOURS",
            "BIKE TOURS",
            "QUAD & ATV TOURS",
            "JEEP & 4WD TOURS",
            "MOTORCYCLE TOURS",
            "AIR & HELICOPTER TOURS",
            "SAILING TRIPS & BOAT TOURS",
            "ACTIVITIES",
            "WATER SPORTS",
            "SURFING LESSONS",
            "CANOE & KAYAK TOURS",
            "SWIM WITH DOLPHINS",
            "RIVER RAFTING",
            "OUTDOOR SPORTS",
            "CLIMBING",
            "GOLF",
            "MOUNTAINBIKING",
            "MOUNTAINEERING",
            "RACING & DREAM CARS",
            "EXTREME SPORTS & ADRENALINE",
            "PAINTBALL",
            "ZIP-LINE ADVENTURES",
            "SNOW & WINTER SPORTS",
            "SCOOTERS & MOTORCYCLES",
            "SKI & SNOWBOARD",
            "BIKES",
            "ICE CLIMBING",
            "PADDLEBOARDING",
            "BOXING TICKETS",
            "SPORTING VENUES",
            "RUNNING",
            "OFF THE BEATEN TRACK",
            "SPORTS FIELD",
            "STADIUM",
            "CAMP SITE",
            "MOTORSPORTS",
            "DOING_SPORTS",
            "SKYDIVING",
            "Experiential",
            "URBAN EXPLORATION",
            "UNIQUE EXPERIENCES",
            "DINING EXPERIENCES",
            "ONCE IN A LIFETIME EXPERIENCES",
            "EXPERIENCES",
            "Slow-Travel",
            "PHOTOGRAPHY TOURS",
            "SHORE EXCURSIONS",
            "ANIMAL USE",
            "CLASSES & WORKSHOPS",
            "CRUISES, SAILING & WATER TOURS",
            "DAY TRIPS & EXCURSIONS",
            "VIATOR VIP & EXCLUSIVE TOURS",
            "MULTI-DAY & EXTENDED TOURS",
            "CLASSES/WORKSHOPS",
            "SLOW TRAVEL",
            "BIKE",
            "BIKING",
            "CULTURAL EVENTS",
            "Budget-Boutique",
            "HOP-ON HOP-OFF TOURS",
            "FREE TOURS",
            "BUDGET",
            "PUBLIC TRANSPORTATION TICKET",
            "SIGHTSEEING TICKETS & PASSES",
            "BUDGET-FRIENDLY",
            "BICYCLE RENTAL",
            "FREE",
            "Backpacker",
            "Luxury",
            "PRIVATE CAR TOURS",
            "SHOPPING TOURS",
            "BOATS & YACHTS",
            "LUXURY & SPECIAL OCCASIONS",
            "NIGHT CLUB",
            "All-Inclusive",
            "BUS & MINIVAN TOURS",
            "TRANSPORTATION",
            "AIRPORT TRANSFERS",
            "GROUP ACTIVITIES",
            "SMALL GROUP",
            "CITY PACKAGES",
            "DINNER PACKAGES",
            "SIGHTSEEING PACKAGES",
            "SPORTING EVENTS & PACKAGES",
            "ENTERTAINMENT PACKAGES",
            "WEDDING PACKAGES",
            "FITNESS",
            "PACKAGES",
            "Guided-Tour",
            "AUDIO GUIDES",
            "FIRST TIME VISITORS",
            "SELF-GUIDED TOURS & RENTALS",
            "AUDIO GUIDED TOURS",
            "VIATOR PRIVATE GUIDES",
            "PRIVATE GUIDED TOURS"
        ]
    },
    "66fada0774e11c042f3c8d5e": {
        "country": "Mexico",
        "countryCd": "MX",
        "locations": [
            "Cabo San Lucas",
            "Loreto",
            "Mulegé",
            "Comondú",
            "La Paz"
        ],
        "experiences": [
            "Bliss",
            "SPAS & WELLNESS",
            "SIGHT-JOGGING",
            "WELLNESS & SPAS",
            "DAY SPA",
            "FITNESS & HEALTH",
            "SPIRITUAL WELLNESS",
            "HOT SPRINGS",
            "JAZZ",
            "WHEELCHAIR ACCESSIBLE",
            "SPA TOURS",
            "RELAXING",
            "WELLNESS",
            "SANDY BEACH",
            "GARDEN",
            "SPA",
            "SWIMMING",
            "Cultural Immersion",
            "CASTLE & PALACE TOURS",
            "LOCAL FLAVOR & NEIGHBORHOOD TOURS",
            "CULTURE & HISTORY",
            "ART & MUSEUMS",
            "ARCHITECTURE",
            "GRAFFITI & URBAN ART",
            "ARCHAEOLOGY",
            "HISTORY & HERITAGE",
            "MEET THE LOCALS",
            "SIGHTSEEING ATTRACTION TICKETS",
            "PEDICAB & RICKSHAW TOURS",
            "CAMEL RIDING TOURS",
            "CARNIVAL ACTIVITIES",
            "CHURCHES & CATHEDRALS",
            "COLD WAR",
            "LOCAL LANGUAGE",
            "SECOND WORLD WAR",
            "UNESCO SITES",
            "ART NOUVEAU",
            "FESTIVAL OF LIGHTS",
            "CULTURAL & THEME TOURS",
            "DISCOVERING",
            "SIGHTSEEING",
            "HIDDEN GEM",
            "HISTORICAL",
            "HERITAGE",
            "ARTWORK",
            "MUSEUMS",
            "SCENIC OUTLOOK",
            "FILMING LOCATION",
            "ART GALLERY",
            "BRIDGE",
            "MONUMENT",
            "SHOPPING STREET",
            "STREET ART",
            "MUSEUM",
            "Romance",
            "BALLOON TOURS",
            "CRUISES & BOAT TOURS",
            "RIVER & HARBOR CRUISES",
            "BEACH TRIPS",
            "ROMANCE & SPECIAL OCCASIONS",
            "WEDDING PROPOSALS",
            "HONEYMOON",
            "DINNER PACKAGE",
            "WINE TASTING & WINERY TOURS",
            "DINNER & LUNCH CRUISES",
            "SHOWS & MUSICALS",
            "DINNER SHOWS",
            "ADULTS ONLY",
            "CONCERTS & OPERAS",
            "VALENTINE'S DAY",
            "ROMANTIC",
            "PRIVATE EXPERIENCES",
            "COUPLES",
            "ROMANTIC TOURS",
            "OUTDOOR SEATING",
            "THEATER",
            "BEACH",
            "Natural Wonders",
            "OUTDOORS",
            "NATURE TRAIL",
            "WILDLIFE",
            "BIRD WATCHING",
            "BIRD SANCTUARY",
            "DIVING",
            "CLIFF DIVING",
            "HIKING",
            "BOAT TOURS & WATER SPORTS",
            "NATURE & PARKS",
            "OUTDOOR ACTIVITIES",
            "NATURE & ADVENTURE",
            "NATIONAL PARKS",
            "DESERT SAFARIS",
            "SAFARIS & WILDLIFE ACTIVITIES",
            "NATURE & PANORAMA",
            "BIRDWATCHING",
            "DOLPHIN & WHALE WATCHING",
            "SNORKELING",
            "TREKKING",
            "NATURAL ATTRACTIONS & NATIONAL PARKS",
            "GARDEN & PARK TOURS",
            "GARDENS & FLOWERS",
            "JUNGLE TOURS",
            "VOLCANO ACTIVITIES",
            "VIEWING POINTS",
            "SUNRISE TOURS",
            "ECOTOURISM",
            "SUNSET TOURS",
            "GLACIER EXPLORATION",
            "CAVE EXPLORATION",
            "NORTHERN LIGHTS",
            "AURORA BOREALIS",
            "NATURE & WILDLIFE",
            "Family",
            "SIGHTSEEING TOURS",
            "THEME TOURS",
            "CITY CARDS",
            "SLEIGH RIDES",
            "THEME PARKS & AMUSEMENT PARKS",
            "ZOO & AQUARIUM",
            "SOCCER TICKETS",
            "HORSE & CARRIAGE TOURS",
            "EDUCATIONAL ACTIVITIES",
            "CHILDREN'S ACTIVITIES",
            "DEALS & DISCOUNTS",
            "HARRY POTTER TOURS",
            "FAMILY-FRIENDLY",
            "GONDOLA TOURS",
            "ICE CREAM",
            "MULTIPLE ATTRACTION POI",
            "THEME PARKS",
            "FAMILY-FRIENDLY SHOWS",
            "FAMILY FRIENDLY",
            "KID FRIENDLY",
            "PLAYING",
            "THEME PARK",
            "AMUSEMENT PARK",
            "WATER PARK",
            "ZOO",
            "FERRIS WHEEL",
            "Festivals & Parties",
            "NIGHT TOURS",
            "HALLOWEEN ACTIVITIES",
            "CULINARY & NIGHTLIFE",
            "FOOD & DRINKS",
            "NIGHTLIFE & BARS",
            "PUB CRAWLS & BAR TOURS",
            "NIGHTCLUB TOURS",
            "NIGHTCLUB TICKETS",
            "MUSICALS",
            "PARTY TOURS",
            "CABARET",
            "STREET MUSIC",
            "THE BEATLES",
            "LUAUS",
            "HOLIDAY & SEASONAL TOURS",
            "NIGHTLIFE",
            "GOING OUT",
            "CONCERTS & SHOWS",
            "EVENTS",
            "FUN & GAMES",
            "Gastronomy",
            "FOOD & GOURMET TOURS",
            "WHISKEY TOURS",
            "COOKING CLASSES",
            "TAPAS",
            "CHOCOLATE",
            "STREET FOOD",
            "PASTRY TOURS",
            "COFFEE TOURS",
            "CRÊPES",
            "PAELLA",
            "LOCAL FOOD",
            "FOOD, WINE & NIGHTLIFE",
            "eating",
            "restaurant",
            "cafe",
            "Adventure",
            "WALKING TOURS",
            "SEGWAY TOURS",
            "BIKE TOURS",
            "QUAD & ATV TOURS",
            "JEEP & 4WD TOURS",
            "MOTORCYCLE TOURS",
            "AIR & HELICOPTER TOURS",
            "SAILING TRIPS & BOAT TOURS",
            "ACTIVITIES",
            "WATER SPORTS",
            "SURFING LESSONS",
            "CANOE & KAYAK TOURS",
            "SWIM WITH DOLPHINS",
            "RIVER RAFTING",
            "OUTDOOR SPORTS",
            "CLIMBING",
            "GOLF",
            "MOUNTAINBIKING",
            "MOUNTAINEERING",
            "RACING & DREAM CARS",
            "EXTREME SPORTS & ADRENALINE",
            "PAINTBALL",
            "ZIP-LINE ADVENTURES",
            "SNOW & WINTER SPORTS",
            "SCOOTERS & MOTORCYCLES",
            "SKI & SNOWBOARD",
            "BIKES",
            "ICE CLIMBING",
            "PADDLEBOARDING",
            "BOXING TICKETS",
            "SPORTING VENUES",
            "RUNNING",
            "OFF THE BEATEN TRACK",
            "SPORTS FIELD",
            "STADIUM",
            "CAMP SITE",
            "MOTORSPORTS",
            "DOING_SPORTS",
            "SKYDIVING",
            "Experiential",
            "URBAN EXPLORATION",
            "UNIQUE EXPERIENCES",
            "DINING EXPERIENCES",
            "ONCE IN A LIFETIME EXPERIENCES",
            "EXPERIENCES",
            "Slow-Travel",
            "PHOTOGRAPHY TOURS",
            "SHORE EXCURSIONS",
            "ANIMAL USE",
            "CLASSES & WORKSHOPS",
            "CRUISES, SAILING & WATER TOURS",
            "DAY TRIPS & EXCURSIONS",
            "VIATOR VIP & EXCLUSIVE TOURS",
            "MULTI-DAY & EXTENDED TOURS",
            "CLASSES/WORKSHOPS",
            "SLOW TRAVEL",
            "BIKE",
            "BIKING",
            "CULTURAL EVENTS",
            "Budget-Boutique",
            "HOP-ON HOP-OFF TOURS",
            "FREE TOURS",
            "BUDGET",
            "PUBLIC TRANSPORTATION TICKET",
            "SIGHTSEEING TICKETS & PASSES",
            "BUDGET-FRIENDLY",
            "BICYCLE RENTAL",
            "FREE",
            "Backpacker",
            "Luxury",
            "PRIVATE CAR TOURS",
            "SHOPPING TOURS",
            "BOATS & YACHTS",
            "LUXURY & SPECIAL OCCASIONS",
            "NIGHT CLUB",
            "All-Inclusive",
            "BUS & MINIVAN TOURS",
            "TRANSPORTATION",
            "AIRPORT TRANSFERS",
            "GROUP ACTIVITIES",
            "SMALL GROUP",
            "CITY PACKAGES",
            "DINNER PACKAGES",
            "SIGHTSEEING PACKAGES",
            "SPORTING EVENTS & PACKAGES",
            "ENTERTAINMENT PACKAGES",
            "WEDDING PACKAGES",
            "FITNESS",
            "PACKAGES",
            "Guided-Tour",
            "AUDIO GUIDES",
            "FIRST TIME VISITORS",
            "SELF-GUIDED TOURS & RENTALS",
            "AUDIO GUIDED TOURS",
            "VIATOR PRIVATE GUIDES",
            "PRIVATE GUIDED TOURS"
        ]
    },
    "66baaaed76ca6c6f00766ab6": {
        "country": "Fiji",
        "countryCd": "FJ",
        "locations": [
            "Fiji",
            "Natadola Beach",
            "Tokoriki Island",
            "Tonge",
            "Northern Division",
            "Denarau Island",
            "Nananu-i-Ra",
            "Tau",
            "Qalito Island",
            "Suva",
            "Bekana Island",
            "Matei",
            "Viti Levu",
            "Tavuki",
            "Ono Island",
            "Namaqumaqua",
            "Vomo",
            "Nacula Island",
            "Beqa Island",
            "Lautoka",
            "Levuka",
            "Bounty Island",
            "Korolevu",
            "Navala",
            "Mamanuca Islands",
            "Sigatoka",
            "Viseisei",
            "Tagaqe",
            "Matamanoa Island",
            "Beqa",
            "Naigani",
            "Dawasamu",
            "Wakaya",
            "Mana Island",
            "Naviti Island",
            "Coral Coast",
            "Yaukuve Levu Island",
            "Nadi",
            "Western Division",
            "Waiyevo",
            "Nawi",
            "Korotogo",
            "Matagi Island",
            "Fiji",
            "Biausevu",
            "Lomaiviti",
            "Macuata",
            "Vanua Levu",
            "Rakiraki",
            "Toberua Island",
            "Ellington Wharf",
            "Nasau",
            "Lomowai",
            "Nanuya Lailai Island",
            "Namatakula",
            "Pacific Harbour",
            "Nasinu",
            "Labasa",
            "Waya",
            "Sanasana",
            "Taveuni Island",
            "Nanuya Balavu Island",
            "Ovalau",
            "Deuba",
            "Abaca",
            "Yanggeta Island",
            "Treasure Island",
            "Beachcomber Island",
            "Naukacuvu Island",
            "Cuvu",
            "Malolo Lailai Island",
            "Kadavu",
            "Yanuca Island",
            "Naweni",
            "Drawaqa Island",
            "Viwa",
            "Malolo Island",
            "Savusavu",
            "Momi",
            "Yasawa Island",
            "Royal Davui Island Resort",
            "Suncoast"
        ],
        "experiences": [
            "Adventure",
            "WALKING TOURS",
            "SEGWAY TOURS",
            "BIKE TOURS",
            "ARCHAEOLOGY",
            "NATURE & ADVENTURE",
            "QUAD & ATV TOURS",
            "JEEP & 4WD TOURS",
            "SAFARIS & WILDLIFE ACTIVITIES",
            "MOTORCYCLE TOURS",
            "AIR & HELICOPTER TOURS",
            "SAILING TRIPS & BOAT TOURS",
            "ACTIVITIES",
            "WATER SPORTS",
            "DIVING",
            "SNORKELING",
            "SURFING LESSONS",
            "CANOE & KAYAK TOURS",
            "SWIM WITH DOLPHINS",
            "RIVER RAFTING",
            "OUTDOOR SPORTS",
            "HIKING",
            "TREKKING",
            "CLIMBING",
            "GOLF",
            "MOUNTAINBIKING",
            "MOUNTAINEERING",
            "RACING & DREAM CARS",
            "EXTREME SPORTS & ADRENALINE",
            "PAINTBALL",
            "ZIP-LINE ADVENTURES",
            "FITNESS & HEALTH",
            "SNOW & WINTER SPORTS",
            "SCOOTERS & MOTORCYCLES",
            "SKI & SNOWBOARD",
            "BIKES",
            "ICE CLIMBING",
            "PADDLEBOARDING",
            "BOXING TICKETS",
            "VOLCANO ACTIVITIES",
            "SPORTING VENUES",
            "RUNNING",
            "OFF THE BEATEN TRACK",
            "GLACIER EXPLORATION",
            "CAVE EXPLORATION",
            "OUTDOOR ACTIVITIES",
            "SPORTS FIELD",
            "SWIMMING",
            "STADIUM",
            "BEACH",
            "CAMP SITE",
            "SIGHTSEEING",
            "MOTORSPORTS",
            "DOING_SPORTS",
            "SKYDIVING",
            "Cultural Immersion",
            "CASTLE & PALACE TOURS",
            "LOCAL FLAVOR & NEIGHBORHOOD TOURS",
            "CULTURE & HISTORY",
            "ART & MUSEUMS",
            "ARCHITECTURE",
            "GRAFFITI & URBAN ART",
            "HISTORY & HERITAGE",
            "MEET THE LOCALS",
            "SIGHTSEEING ATTRACTION TICKETS",
            "PEDICAB & RICKSHAW TOURS",
            "CAMEL RIDING TOURS",
            "CARNIVAL ACTIVITIES",
            "CHURCHES & CATHEDRALS",
            "COLD WAR",
            "LOCAL LANGUAGE",
            "SECOND WORLD WAR",
            "UNESCO SITES",
            "ART NOUVEAU",
            "FESTIVAL OF LIGHTS",
            "CULTURAL & THEME TOURS",
            "DISCOVERING",
            "HIDDEN GEM",
            "HISTORICAL",
            "HERITAGE",
            "ARTWORK",
            "MUSEUMS",
            "SCENIC OUTLOOK",
            "FILMING LOCATION",
            "ART GALLERY",
            "BRIDGE",
            "MONUMENT",
            "SHOPPING STREET",
            "STREET ART",
            "MUSEUM",
            "Romance",
            "BALLOON TOURS",
            "CRUISES & BOAT TOURS",
            "RIVER & HARBOR CRUISES",
            "BEACH TRIPS",
            "WELLNESS & SPAS",
            "ROMANCE & SPECIAL OCCASIONS",
            "WEDDING PROPOSALS",
            "HONEYMOON",
            "DINNER PACKAGE",
            "WINE TASTING & WINERY TOURS",
            "DINNER & LUNCH CRUISES",
            "SHOWS & MUSICALS",
            "DINNER SHOWS",
            "ADULTS ONLY",
            "CONCERTS & OPERAS",
            "VALENTINE'S DAY",
            "ROMANTIC",
            "PRIVATE EXPERIENCES",
            "COUPLES",
            "ROMANTIC TOURS",
            "OUTDOOR SEATING",
            "THEATER",
            "SPA",
            "SPAS & WELLNESS",
            "Natural Wonders",
            "OUTDOORS",
            "NATURE TRAIL",
            "WILDLIFE",
            "BIRD WATCHING",
            "BIRD SANCTUARY",
            "CLIFF DIVING",
            "BOAT TOURS & WATER SPORTS",
            "NATURE & PARKS",
            "NATIONAL PARKS",
            "DESERT SAFARIS",
            "NATURE & PANORAMA",
            "BIRDWATCHING",
            "DOLPHIN & WHALE WATCHING",
            "NATURAL ATTRACTIONS & NATIONAL PARKS",
            "GARDEN & PARK TOURS",
            "GARDENS & FLOWERS",
            "JUNGLE TOURS",
            "HOT SPRINGS",
            "VIEWING POINTS",
            "SUNRISE TOURS",
            "ECOTOURISM",
            "SUNSET TOURS",
            "NORTHERN LIGHTS",
            "AURORA BOREALIS",
            "NATURE & WILDLIFE",
            "Festivals & Parties",
            "NIGHT TOURS",
            "HALLOWEEN ACTIVITIES",
            "CULINARY & NIGHTLIFE",
            "FOOD & DRINKS",
            "NIGHTLIFE & BARS",
            "PUB CRAWLS & BAR TOURS",
            "NIGHTCLUB TOURS",
            "NIGHTCLUB TICKETS",
            "MUSICALS",
            "PARTY TOURS",
            "JAZZ",
            "CABARET",
            "STREET MUSIC",
            "THE BEATLES",
            "LUAUS",
            "HOLIDAY & SEASONAL TOURS",
            "NIGHTLIFE",
            "GOING OUT",
            "CONCERTS & SHOWS",
            "EVENTS",
            "FUN & GAMES",
            "Family",
            "SIGHTSEEING TOURS",
            "THEME TOURS",
            "CITY CARDS",
            "SLEIGH RIDES",
            "THEME PARKS & AMUSEMENT PARKS",
            "ZOO & AQUARIUM",
            "SOCCER TICKETS",
            "HORSE & CARRIAGE TOURS",
            "EDUCATIONAL ACTIVITIES",
            "CHILDREN'S ACTIVITIES",
            "DEALS & DISCOUNTS",
            "HARRY POTTER TOURS",
            "WHEELCHAIR ACCESSIBLE",
            "FAMILY-FRIENDLY",
            "GONDOLA TOURS",
            "ICE CREAM",
            "MULTIPLE ATTRACTION POI",
            "THEME PARKS",
            "FAMILY-FRIENDLY SHOWS",
            "FAMILY FRIENDLY",
            "KID FRIENDLY",
            "PLAYING",
            "THEME PARK",
            "AMUSEMENT PARK",
            "WATER PARK",
            "ZOO",
            "FERRIS WHEEL",
            "Gastronomy",
            "FOOD & GOURMET TOURS",
            "WHISKEY TOURS",
            "COOKING CLASSES",
            "TAPAS",
            "CHOCOLATE",
            "STREET FOOD",
            "PASTRY TOURS",
            "COFFEE TOURS",
            "CRÊPES",
            "PAELLA",
            "LOCAL FOOD",
            "FOOD, WINE & NIGHTLIFE",
            "eating",
            "restaurant",
            "cafe",
            "Bliss",
            "SIGHT-JOGGING",
            "DAY SPA",
            "SPIRITUAL WELLNESS",
            "SPA TOURS",
            "RELAXING",
            "WELLNESS",
            "SANDY BEACH",
            "GARDEN",
            "Experiential",
            "URBAN EXPLORATION",
            "UNIQUE EXPERIENCES",
            "DINING EXPERIENCES",
            "ONCE IN A LIFETIME EXPERIENCES",
            "EXPERIENCES",
            "Slow-Travel",
            "PHOTOGRAPHY TOURS",
            "SHORE EXCURSIONS",
            "ANIMAL USE",
            "CLASSES & WORKSHOPS",
            "CRUISES, SAILING & WATER TOURS",
            "DAY TRIPS & EXCURSIONS",
            "VIATOR VIP & EXCLUSIVE TOURS",
            "MULTI-DAY & EXTENDED TOURS",
            "CLASSES/WORKSHOPS",
            "SLOW TRAVEL",
            "BIKE",
            "BIKING",
            "CULTURAL EVENTS",
            "Luxury",
            "PRIVATE CAR TOURS",
            "SHOPPING TOURS",
            "BOATS & YACHTS",
            "LUXURY & SPECIAL OCCASIONS",
            "NIGHT CLUB",
            "Budget-Boutique",
            "HOP-ON HOP-OFF TOURS",
            "FREE TOURS",
            "BUDGET",
            "PUBLIC TRANSPORTATION TICKET",
            "SIGHTSEEING TICKETS & PASSES",
            "BUDGET-FRIENDLY",
            "BICYCLE RENTAL",
            "FREE",
            "Backpacker",
            "All-Inclusive",
            "BUS & MINIVAN TOURS",
            "TRANSPORTATION",
            "AIRPORT TRANSFERS",
            "GROUP ACTIVITIES",
            "SMALL GROUP",
            "CITY PACKAGES",
            "DINNER PACKAGES",
            "SIGHTSEEING PACKAGES",
            "SPORTING EVENTS & PACKAGES",
            "ENTERTAINMENT PACKAGES",
            "WEDDING PACKAGES",
            "FITNESS",
            "PACKAGES",
            "Guided-Tour",
            "AUDIO GUIDES",
            "FIRST TIME VISITORS",
            "SELF-GUIDED TOURS & RENTALS",
            "AUDIO GUIDED TOURS",
            "VIATOR PRIVATE GUIDES",
            "PRIVATE GUIDED TOURS",
            "Cultural & History",
            "LOCAL CULTURE"
        ]
    },
    "6320cf34f407c88881e3ad6a": {
        "country": "Dominican Republic",
        "countryCd": "DO",
        "locations": [
            "Dominican Republic",
            "Hato Mayor del Rey",
            "Esperanza",
            "San Francisco de Macoris",
            "El Seibo",
            "Mano Juan",
            "Altamira",
            "Pedro Brand",
            "San Jose de Las Matas",
            "Constanza",
            "Puerto Plata",
            "Barahona",
            "Trinidad",
            "Bisonó",
            "Higuey",
            "Los Limones",
            "Cayo Arena",
            "Cotui",
            "Samana",
            "Sabana De La Mar",
            "Santo Domingo Oeste",
            "Sosúa",
            "Los Róbalos",
            "Barahona Province",
            "Lake Enriquillo",
            "Ramon Santana",
            "Licey al Medio",
            "Santiago De Los Caballeros",
            "Los Patos",
            "Cabrera",
            "Santiago Province",
            "La Romana",
            "Las Terrenas",
            "Pedernales",
            "Las Galeras",
            "Pedernales Province",
            "Imbert",
            "Puñal",
            "Santo Domingo Este",
            "San Pedro de Macorís Province",
            "Azua",
            "Río San Juan",
            "Dominicaanse Republiek",
            "Baní",
            "Río Grande",
            "San Felipe de Puerto Plata",
            "Polo",
            "Gaspar Hernandez",
            "Hato Mayor Province",
            "Sabana Grande de Boyá",
            "Punta Cana",
            "Puerto Plata Province",
            "Los Alcarrizos",
            "Brisa del Este",
            "Cabarete",
            "Miches",
            "Sabana Larga",
            "San Rafael de Yuma",
            "Bonao",
            "Rancho Español",
            "La Romana Province",
            "Damajagua",
            "Boca de Yuma",
            "Monte Coca",
            "La Vega",
            "Santo Domingo",
            "Bayahíbe",
            "Punta Rucia",
            "Boca Chica",
            "Montecristi",
            "La Altagracia Province",
            "Paraiso",
            "Jarabacoa",
            "Luperon",
            "Punta Balandra",
            "Juan Dolio",
            "Guayacanes",
            "La Cienaga",
            "Santo Domingo Norte",
            "Monte Plata Province",
            "El Valle",
            "Dominican Republic",
            "Samaná Province",
            "Cristóbal",
            "Nagua",
            "Sanchez"
        ]
    },
    "61a531c62841483f173e957b": {
        "country": "Jordan",
        "countryCd": "JO",
        "locations": [
            "Jordan",
            "As-Salt",
            "Juwafat al-Kafrayn",
            "Amman",
            "Al Mokhaba Al Tahta",
            "Der Abi Saeed",
            "Umm el-Jimal",
            "Wadi al Mujib",
            "Umm Qais",
            "Swemeh",
            "Jerash",
            "At-Tafilah",
            "Ajloun",
            "Aqaba",
            "Madaba",
            "Jordan",
            "Azraq",
            "Al-Azraq Al-Shamaly",
            "Wadi Rum Village",
            "Petra",
            "Irbid",
            "Tabqet Fahel",
            "Dead Sea",
            "Borma",
            "Wadi Musa",
            "Dana",
            "Quairah District",
            "Aqaba Governorate",
            "Ma'in",
            "Kerak",
            "Al Jaya",
            "Al Rama",
            "At-Taybeh",
            "Ma'an Governorate",
            "Petra",
            "Zarqa",
            "Mastaba",
            "Shobak"
        ],
        "experiences": [
            "Active/Adventure",
            "TOURS",
            "SIGHTSEEING TOURS",
            "BUS & MINIVAN TOURS",
            "ARCHAEOLOGY",
            "NATURE & ADVENTURE",
            "DESERT SAFARIS",
            "JEEP & 4WD TOURS",
            "SAFARIS & WILDLIFE ACTIVITIES",
            "MEDIUM-RISK ACTIVITIES",
            "OUTDOOR ACTIVITIES",
            "SIGHTSEEING",
            "ACTIVITIES",
            "History & Archaeology",
            "CULTURE & HISTORY",
            "ART & MUSEUMS",
            "HISTORY & HERITAGE",
            "HISTORICAL & HERITAGE TOURS",
            "LITERARY, ART & MUSIC TOURS",
            "ARCHAEOLOGY TOURS",
            "Cultural Immersion/Meaningful Travel",
            "NIGHT TOURS",
            "MEET THE LOCALS",
            "WORKSHOPS & CLASSES",
            "ART & CRAFT WORKSHOPS",
            "CLASSES & WORKSHOPS",
            "CULTURAL TOURS",
            "STREET FOOD TOURS",
            "MARKET TOURS",
            "ECO TOURS",
            "SUSTAINABLE TOURS",
            "VOLUNTEER TOURS",
            "CULTURE",
            "HISTORY",
            "LOCAL",
            "Spiritual & Faith",
            "RELIGIOUS & SPIRITUAL ACTIVITIES",
            "SPIRITUAL WELLNESS",
            "SIGHTSEEING PASSES",
            "SIGHTSEEING PACKAGES",
            "SPIRITUAL",
            "FAITH",
            "Romance",
            "ROMANCE & SPECIAL OCCASIONS",
            "CRUISES & BOAT TOURS",
            "RIVER & HARBOR CRUISES",
            "WEDDING PROPOSALS",
            "HONEYMOON",
            "WEDDINGS & HONEYMOONS",
            "ROMANTIC TOURS",
            "DANCE LESSONS",
            "ROMANTIC",
            "OUTDOOR SEATING",
            "THEATER",
            "BEACH",
            "BEACHES",
            "SPA",
            "SHOPPING STREET",
            "SPAS & WELLNESS",
            "SCENIC VIEW",
            "SPECIAL OCCASIONS",
            "Natural Wonders",
            "NATURE & PANORAMA",
            "NATURAL ATTRACTIONS & NATIONAL PARKS",
            "NATURE RESERVE",
            "AIR, HELICOPTER & BALLOON TOURS",
            "CRUISES, SAILING & WATER TOURS",
            "NATURE & WILDLIFE",
            "OUTDOORS",
            "NATURE TRAIL",
            "WILDLIFE",
            "DIVING",
            "HIKING",
            "BOAT TOURS & WATER SPORTS",
            "NATURE & PARKS",
            "Family",
            "THEME TOURS",
            "CITY CARDS",
            "SLEIGH RIDES",
            "THEME PARKS & AMUSEMENT PARKS",
            "ZOO & AQUARIUM",
            "SOCCER TICKETS",
            "HORSE & CARRIAGE TOURS",
            "CAMEL RIDING TOURS",
            "EDUCATIONAL ACTIVITIES",
            "CHILDREN'S ACTIVITIES",
            "DEALS & DISCOUNTS",
            "HARRY POTTER TOURS",
            "WHEELCHAIR ACCESSIBLE",
            "FAMILY-FRIENDLY",
            "GONDOLA TOURS",
            "ICE CREAM",
            "MULTIPLE ATTRACTION POI",
            "THEME PARKS",
            "FAMILY-FRIENDLY SHOWS",
            "ZOOS & AQUARIUMS",
            "FAMILY FRIENDLY",
            "KID FRIENDLY",
            "PLAYING",
            "THEME PARK",
            "AMUSEMENT PARK",
            "WATER PARK",
            "ZOO",
            "FERRIS WHEEL",
            "SWIMMING",
            "Gastronomy",
            "CULINARY & NIGHTLIFE",
            "FOOD & DRINKS",
            "WINE TASTING & WINERY TOURS",
            "FOOD & GOURMET TOURS",
            "WHISKEY TOURS",
            "COOKING CLASSES",
            "DINNER & LUNCH CRUISES",
            "DINNER SHOWS",
            "TAPAS",
            "CHOCOLATE",
            "STREET FOOD",
            "PASTRY TOURS",
            "COFFEE TOURS",
            "CRÊPES",
            "PAELLA",
            "LOCAL FOOD",
            "FOOD, WINE & NIGHTLIFE",
            "eating",
            "restaurant",
            "cafe",
            "WELLNESS & SPAS",
            "DAY SPA",
            "SPA TOURS",
            "Meetings/Business",
            "EXHIBITIONS",
            "SIM CARDS",
            "Meaningful/Sustainable Travel",
            "MUSEUMS & EXHIBITIONS",
            "ANIMAL SANCTUARY",
            "Adventure",
            "WALKING TOURS",
            "SEGWAY TOURS",
            "BIKE TOURS",
            "QUAD & ATV TOURS",
            "MOTORCYCLE TOURS",
            "AIR & HELICOPTER TOURS",
            "SAILING TRIPS & BOAT TOURS",
            "WATER SPORTS",
            "SNORKELING",
            "SURFING LESSONS",
            "CANOE & KAYAK TOURS",
            "SWIM WITH DOLPHINS",
            "RIVER RAFTING",
            "OUTDOOR SPORTS",
            "TREKKING",
            "CLIMBING",
            "GOLF",
            "MOUNTAINBIKING",
            "MOUNTAINEERING",
            "RACING & DREAM CARS",
            "EXTREME SPORTS & ADRENALINE",
            "PAINTBALL",
            "ZIP-LINE ADVENTURES",
            "FITNESS & HEALTH",
            "SNOW & WINTER SPORTS",
            "SCOOTERS & MOTORCYCLES",
            "SKI & SNOWBOARD",
            "BIKES",
            "ICE CLIMBING",
            "PADDLEBOARDING",
            "BOXING TICKETS",
            "VOLCANO ACTIVITIES",
            "SPORTING VENUES",
            "RUNNING",
            "OFF THE BEATEN TRACK",
            "GLACIER EXPLORATION",
            "CAVE EXPLORATION",
            "SAILING TRIPS & TOURS",
            "SPORTS FIELD",
            "STADIUM",
            "CAMP SITE",
            "MOTORSPORTS",
            "DOING_SPORTS",
            "SKYDIVING",
            "Religion & Faith",
            "MUSEUM TICKETS",
            "ANCIENT HISTORY",
            "MUSEUM TICKETS & PASSES",
            "Experiential",
            "NEIGHBORHOOD TOURS",
            "ARCHITECTURE",
            "URBAN EXPLORATION",
            "VIEWING POINTS",
            "UNIQUE EXPERIENCES",
            "DINING EXPERIENCES",
            "ONCE IN A LIFETIME EXPERIENCES",
            "Slow-Travel",
            "PHOTOGRAPHY TOURS",
            "SHORE EXCURSIONS",
            "SUNRISE TOURS",
            "SUNSET TOURS",
            "ANIMAL USE",
            "DAY TRIPS & EXCURSIONS",
            "VIATOR VIP & EXCLUSIVE TOURS",
            "MULTI-DAY & EXTENDED TOURS",
            "RELAXING",
            "SLOW TRAVEL",
            "BIKE",
            "BIKING",
            "CLASSES/WORKSHOPS",
            "CULTURAL EVENTS",
            "Luxury",
            "PRIVATE CAR TOURS",
            "SHOPPING TOURS",
            "CONCERTS & OPERAS",
            "BOATS & YACHTS",
            "PRIVATE EXPERIENCES",
            "LUXURY & SPECIAL OCCASIONS",
            "AIRPLANE TOURS",
            "HELICOPTER TOURS",
            "LUXURY TOURS",
            "NIGHT CLUB",
            "Backpacker",
            "SIGHT-JOGGING",
            "FREE TOURS",
            "BUDGET",
            "SIGHTSEEING TICKETS & PASSES",
            "BUDGET-FRIENDLY",
            "BICYCLE RENTAL",
            "FREE",
            "Guided-Tour",
            "AUDIO GUIDES",
            "GROUP ACTIVITIES",
            "FIRST TIME VISITORS",
            "SELF-GUIDED TOURS & RENTALS",
            "AUDIO GUIDED TOURS",
            "VIATOR PRIVATE GUIDES",
            "PRIVATE GUIDED TOURS",
            "MUSEUMS",
            "DISCOVERING",
            "Eco Travel",
            "ECOTOURISM",
            "ECO CERTIFIED",
            "Wellness",
            "HOT SPRINGS",
            "JAZZ",
            "SANDY BEACH",
            "GARDEN",
            "Cultural & History",
            "CULTURAL & THEME TOURS",
            "LOCAL CULTURE",
            "UNESCO Heritage",
            "UNESCO SITES",
            "4WD, ATV & OFF-ROAD TOURS",
            "PARAGLIDING",
            "Eco-Tourism",
            "BIRDING",
            "FAMILY-FRIENDLY ACTIVITIES",
            "FAMILY MARKETS",
            "Culinary",
            "BAKING",
            "CHOCOLATE TOURS",
            "DINNER THEATER",
            "FOOD TOURS",
            "COFFEE & TEA TOURS",
            "AFTERNOON TEAS",
            "FISH FRY EXPERIENCE",
            "PRIVATE & CUSTOM TOURS",
            "Beach Trips",
            "Spa & Wellness",
            "DAY SPAS",
            "THERMAL SPAS & HOT SPRINGS",
            "HEALTH & WELLNESS",
            "Desert Excursions",
            "SAFARIS",
            "HIKING & TREKKING",
            "HIKING & CAMPING",
            "WALKING & BIKING TOURS",
            "Canyoning",
            "Hot Air Balloon",
            "BALLOON TOURS",
            "BALLOON RIDES",
            "Astro-Tourism (Star-Gazing)",
            "STARGAZING",
            "City Tours",
            "CITY PACKAGES"
        ]
    },
    "64b1ae3876ca6c6f00766a7a": {
        "country": "Mexico",
        "countryCd": "MX",
        "locations": [
            "Mérida",
            "Valladolid",
            "Progreso",
            "Izamal",
            "Tekax",
            "Río Lagartos",
            "Maní",
            "Sisal",
            "Las Coloradas",
            "San Felipe",
            "Tizimín",
            "El Cuyo",
            "Celestún",
            "Arrecife Alacranes",
            "El Palmar",
            "Temozón",
            "Ekbalam",
            "Uxmal",
            "Dzibilchaltún"
        ],
        "experiences": [
            "Active",
            "WALKING TOURS",
            "SEGWAY TOURS",
            "BIKE TOURS",
            "ARCHAEOLOGY",
            "NATURE & ADVENTURE",
            "QUAD & ATV TOURS",
            "JEEP & 4WD TOURS",
            "SAFARIS & WILDLIFE ACTIVITIES",
            "MOTORCYCLE TOURS",
            "AIR & HELICOPTER TOURS",
            "SAILING TRIPS & BOAT TOURS",
            "ACTIVITIES",
            "WATER SPORTS",
            "DIVING",
            "SNORKELING",
            "SURFING LESSONS",
            "CANOE & KAYAK TOURS",
            "SWIM WITH DOLPHINS",
            "RIVER RAFTING",
            "OUTDOOR SPORTS",
            "HIKING",
            "TREKKING",
            "CLIMBING",
            "GOLF",
            "MOUNTAINBIKING",
            "MOUNTAINEERING",
            "RACING & DREAM CARS",
            "EXTREME SPORTS & ADRENALINE",
            "PAINTBALL",
            "ZIP-LINE ADVENTURES",
            "FITNESS & HEALTH",
            "SNOW & WINTER SPORTS",
            "SCOOTERS & MOTORCYCLES",
            "SKI & SNOWBOARD",
            "BIKES",
            "ICE CLIMBING",
            "PADDLEBOARDING",
            "BOXING TICKETS",
            "VOLCANO ACTIVITIES",
            "SPORTING VENUES",
            "RUNNING",
            "OFF THE BEATEN TRACK",
            "GLACIER EXPLORATION",
            "CAVE EXPLORATION",
            "OUTDOOR ACTIVITIES",
            "SAILING TRIPS & TOURS",
            "SPORTS FIELD",
            "SWIMMING",
            "BEACH",
            "CAMP SITE",
            "SIGHTSEEING",
            "MOTORSPORTS",
            "DOING_SPORTS",
            "SKYDIVING",
            "Cultural Immersion",
            "CASTLE & PALACE TOURS",
            "LOCAL FLAVOR & NEIGHBORHOOD TOURS",
            "CULTURE & HISTORY",
            "ART & MUSEUMS",
            "ARCHITECTURE",
            "GRAFFITI & URBAN ART",
            "HISTORY & HERITAGE",
            "MEET THE LOCALS",
            "SIGHTSEEING ATTRACTION TICKETS",
            "PEDICAB & RICKSHAW TOURS",
            "CAMEL RIDING TOURS",
            "CARNIVAL ACTIVITIES",
            "CHURCHES & CATHEDRALS",
            "COLD WAR",
            "LOCAL LANGUAGE",
            "SECOND WORLD WAR",
            "UNESCO SITES",
            "ART NOUVEAU",
            "FESTIVAL OF LIGHTS",
            "CULTURAL & THEME TOURS",
            "NEIGHBORHOOD TOURS",
            "DISCOVERING",
            "HIDDEN GEM",
            "HISTORICAL",
            "HERITAGE",
            "ARTWORK",
            "MUSEUMS",
            "SCENIC OUTLOOK",
            "FILMING LOCATION",
            "ART GALLERY",
            "BRIDGE",
            "MONUMENT",
            "SHOPPING STREET",
            "STREET ART",
            "MUSEUM",
            "Romance",
            "BALLOON TOURS",
            "CRUISES & BOAT TOURS",
            "RIVER & HARBOR CRUISES",
            "BEACH TRIPS",
            "WELLNESS & SPAS",
            "ROMANCE & SPECIAL OCCASIONS",
            "WEDDING PROPOSALS",
            "HONEYMOON",
            "DINNER PACKAGE",
            "WINE TASTING & WINERY TOURS",
            "DINNER & LUNCH CRUISES",
            "SHOWS & MUSICALS",
            "DINNER SHOWS",
            "ADULTS ONLY",
            "CONCERTS & OPERAS",
            "VALENTINE'S DAY",
            "ROMANTIC",
            "PRIVATE EXPERIENCES",
            "COUPLES",
            "ROMANTIC TOURS",
            "OUTDOOR SEATING",
            "THEATER",
            "SPA",
            "SPAS & WELLNESS",
            "Natural Wonders",
            "OUTDOORS",
            "NATURE TRAIL",
            "WILDLIFE",
            "BIRD WATCHING",
            "BIRD SANCTUARY",
            "CLIFF DIVING",
            "BOAT TOURS & WATER SPORTS",
            "NATURE & PARKS",
            "NATIONAL PARKS",
            "DESERT SAFARIS",
            "NATURE & PANORAMA",
            "BIRDWATCHING",
            "DOLPHIN & WHALE WATCHING",
            "NATURAL ATTRACTIONS & NATIONAL PARKS",
            "GARDEN & PARK TOURS",
            "GARDENS & FLOWERS",
            "JUNGLE TOURS",
            "HOT SPRINGS",
            "VIEWING POINTS",
            "SUNRISE TOURS",
            "ECOTOURISM",
            "SUNSET TOURS",
            "NORTHERN LIGHTS",
            "AURORA BOREALIS",
            "NATURE & WILDLIFE",
            "Festivals & Parties",
            "NIGHT TOURS",
            "HALLOWEEN ACTIVITIES",
            "CULINARY & NIGHTLIFE",
            "FOOD & DRINKS",
            "NIGHTLIFE & BARS",
            "PUB CRAWLS & BAR TOURS",
            "NIGHTCLUB TOURS",
            "NIGHTCLUB TICKETS",
            "MUSICALS",
            "PARTY TOURS",
            "JAZZ",
            "CABARET",
            "STREET MUSIC",
            "THE BEATLES",
            "LUAUS",
            "HOLIDAY & SEASONAL TOURS",
            "NIGHTLIFE",
            "GOING OUT",
            "CONCERTS & SHOWS",
            "EVENTS",
            "FUN & GAMES",
            "Family",
            "SIGHTSEEING TOURS",
            "THEME TOURS",
            "CITY CARDS",
            "SLEIGH RIDES",
            "THEME PARKS & AMUSEMENT PARKS",
            "ZOO & AQUARIUM",
            "SOCCER TICKETS",
            "HORSE & CARRIAGE TOURS",
            "EDUCATIONAL ACTIVITIES",
            "CHILDREN'S ACTIVITIES",
            "DEALS & DISCOUNTS",
            "HARRY POTTER TOURS",
            "WHEELCHAIR ACCESSIBLE",
            "FAMILY-FRIENDLY",
            "GONDOLA TOURS",
            "ICE CREAM",
            "MULTIPLE ATTRACTION POI",
            "THEME PARKS",
            "FAMILY-FRIENDLY SHOWS",
            "ZOOS & AQUARIUMS",
            "FAMILY FRIENDLY",
            "KID FRIENDLY",
            "PLAYING",
            "THEME PARK",
            "AMUSEMENT PARK",
            "WATER PARK",
            "ZOO",
            "FERRIS WHEEL",
            "Gastronomy",
            "FOOD & GOURMET TOURS",
            "WHISKEY TOURS",
            "COOKING CLASSES",
            "TAPAS",
            "CHOCOLATE",
            "STREET FOOD",
            "PASTRY TOURS",
            "COFFEE TOURS",
            "CRÊPES",
            "PAELLA",
            "LOCAL FOOD",
            "FOOD, WINE & NIGHTLIFE",
            "RESTAURANT",
            "WINE BARS",
            "BREWERIES",
            "SIT DOWN",
            "Bliss",
            "SIGHT-JOGGING",
            "DAY SPA",
            "SPIRITUAL WELLNESS",
            "SPA TOURS",
            "RELAXING",
            "WELLNESS",
            "SANDY BEACH",
            "GARDEN",
            "Experiential",
            "URBAN EXPLORATION",
            "UNIQUE EXPERIENCES",
            "DINING EXPERIENCES",
            "ONCE IN A LIFETIME EXPERIENCES",
            "EXPERIENCES",
            "Slow-Travel",
            "PHOTOGRAPHY TOURS",
            "SHORE EXCURSIONS",
            "ANIMAL USE",
            "CLASSES & WORKSHOPS",
            "CRUISES, SAILING & WATER TOURS",
            "DAY TRIPS & EXCURSIONS",
            "VIATOR VIP & EXCLUSIVE TOURS",
            "MULTI-DAY & EXTENDED TOURS",
            "CLASSES/WORKSHOPS",
            "SLOW TRAVEL",
            "BIKE",
            "BIKING",
            "CULTURAL EVENTS",
            "Luxury",
            "PRIVATE CAR TOURS",
            "BOATS & YACHTS",
            "LUXURY & SPECIAL OCCASIONS",
            "AIRPLANE TOURS",
            "HELICOPTER TOURS",
            "NIGHT CLUB",
            "DIVING & SNORKELING",
            "$$$$",
            "BOATING",
            "Budget-Boutique",
            "HOP-ON HOP-OFF TOURS",
            "FREE TOURS",
            "BUDGET",
            "PUBLIC TRANSPORTATION TICKET",
            "SIGHTSEEING TICKETS & PASSES",
            "BUDGET-FRIENDLY",
            "BICYCLE RENTAL",
            "FREE",
            "BICYCLE & SCOOTER RENTALS",
            "ATTRACTIONS",
            "Backpacker",
            "All-Inclusive",
            "BUS & MINIVAN TOURS",
            "TRANSPORTATION",
            "AIRPORT TRANSFERS",
            "GROUP ACTIVITIES",
            "SMALL GROUP",
            "CITY PACKAGES",
            "DINNER PACKAGES",
            "SIGHTSEEING PACKAGES",
            "SPORTING EVENTS & PACKAGES",
            "ENTERTAINMENT PACKAGES",
            "WEDDING PACKAGES",
            "FITNESS",
            "PACKAGES",
            "ALL INCLUSIVE",
            "LIVE ENTERTAINMENT",
            "Guided-Tour",
            "AUDIO GUIDES",
            "FIRST TIME VISITORS",
            "SELF-GUIDED TOURS & RENTALS",
            "AUDIO GUIDED TOURS",
            "VIATOR PRIVATE GUIDES",
            "PRIVATE GUIDED TOURS",
            "Cultural & History",
            "LOCAL CULTURE",
            "Art Museum",
            "ART MUSEUMS",
            "MUSEUMS & EXHIBITIONS",
            "MUSEUM TICKETS & PASSES",
            "ART CLASSES",
            "LITERARY, ART & MUSIC TOURS",
            "ART GALLERIES",
            "ARTS AND CRAFT",
            "INTERACTIVE TOURS & INCENTIVE EVENTS",
            "SCOOTER TOURS",
            "AIRBOAT TOURS",
            "CLASSES",
            "BUNGEE JUMPING",
            "ISLAND TOURS",
            "SNOWSHOE TOURS",
            "WINDSURFING",
            "SKIING TOURS",
            "SPEED & JET BOAT TOURS",
            "TRIKE TOURS",
            "DUCK TOURS",
            "TANK DRIVING",
            "SUBMARINE TOURS",
            "DRIVING EXPERIENCES",
            "JETPACKS",
            "VESPA TOURS",
            "PIRATE TOURS",
            "CENOTE DIVING",
            "NATURE & PANORAMIC TOURS",
            "FISHING TOURS",
            "SHARK DIVING",
            "SEAPLANE",
            "TEAM SPORTS",
            "KITESURFING",
            "PARASAILING",
            "DOLPHIN & WHALEWATCHING TOURS",
            "AIR, HELICOPTER & BALLOON TOURS",
            "TOURS & SIGHTSEEING",
            "WATERSPORTS",
            "SPORTS LESSONS",
            "SIGHTSEEING PASSES",
            "SPORTING EVENT TICKETS & PASSES",
            "ZOO TICKETS & PASSES",
            "Eco-Tourism",
            "ECO CERTIFIED",
            "NATURE RESERVE",
            "ECO TOURS",
            "BIRDING",
            "FAMILY-FRIENDLY ACTIVITIES",
            "FAMILY MARKETS",
            "Culinary",
            "BAKING",
            "STREET FOOD TOURS",
            "MARKET TOURS",
            "CHOCOLATE TOURS",
            "DINNER THEATER",
            "FOOD TOURS",
            "COFFEE & TEA TOURS",
            "AFTERNOON TEAS",
            "FISH FRY EXPERIENCE",
            "BEER BIKE",
            "COMEDY TOURS",
            "SHOWS, CONCERTS & SPORTS",
            "BEER & BREWERY TOURS",
            "NIGHTCLUB PASSES",
            "BARS & PUBS",
            "PRIVATE & CUSTOM TOURS",
            "Spa & Wellness",
            "DAY SPAS",
            "THERMAL SPAS & HOT SPRINGS",
            "HEALTH & WELLNESS"
        ]
    }
}